### ISSUE TITLE
CFPのページ準備

### ISSUE THREAD

**Issue by miurahr** [osmfj/sotmjp2018#16]
Call for presentationの募集ページ および、投稿フォームが必要です。
投稿フォームは、Google Fromsでしょうか？

githubのissueにコメント投稿してもらうスタイルや、様々なアプローチがあるようでう。

他の事例では、CFP app もあるようです。
例 https://github.com/rubycentral/cfp-app
https://github.com/opencfp/opencfp

**Comment by KMR-zoar** [comment]
同じく Google Forms に一票します

**Comment by miurahr** [comment]
Formのほか、スケジュールを示すページが必要です

2018年5月7日(月) 21:54 KMR-zoar <notifications@github.com>:

**Comment by miurahr** [comment]
DONE
