### ISSUE TITLE
タイムテーブルへ発表者とプログラムの登録

### ISSUE THREAD

**Issue by KMR-zoar** [osmfj/sotmjp2018#34]
発表者が決定したのでタイムテーブルを埋める｡

**Comment by miurahr** [comment]
issue34-3  branchをきりました。こちらをそだてていって、完了したら、PRしましょう!

**Comment by KMR-zoar** [comment]
Slcak での打ち合わせを経て公開を行いました。

**Comment by KMR-zoar** [comment]
Stroly様のスポンサー講演を追加するためにタイムテーブル編集します。

**Comment by KMR-zoar** [comment]
イベント終了につき issue をクローズ。
スライドの追加は #60 に紐付けます。
